wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1680217455.399165
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.13
      5: 0.13.10
      8:
      - 3
      - 5
activation:
  desc: null
  value: sigmoid
bc_type:
  desc: null
  value: hard
iterations:
  desc: null
  value:
  - 3000
  - null
learning_rate:
  desc: null
  value:
  - 0.001
  - null
loss_type:
  desc: null
  value: pde
n_layers:
  desc: null
  value: 4
net_type:
  desc: null
  value: USnet
num_samples:
  desc: null
  value: 100
optimizer:
  desc: null
  value:
  - adam
  - L-BFGS
size_layers:
  desc: null
  value: 100
train_distribution:
  desc: null
  value: Hammersley
