wandb_version: 1

activation:
  value: tanh
bc_type:
  value: hard
loss_type:
  value: pde
n_layers:
  value: 10
net_type:
  value: USnet
num_samples:
  value: 100
size_layers:
  value: 75
train_distribution:
  value: Hammersley
